---
- name: "download source code"
  get_url: url={{ ruby_download_location }}
           dest=/usr/local/src/

- name: "generate installation script"
  template: src=install-ruby.j2
            dest=/usr/local/src/install-ruby.sh
            owner=root
            group=root
            mode=700

- name: "run install script"
  command: /usr/local/src/install-ruby.sh
           creates={{ ruby_location }}/bin/ruby

- name: "install bundler"
  command: "{{ ruby_location }}/bin/gem install bundler {{ ruby_bundler_flags }}
            creates={{ ruby_location }}/bin/bundle"
